### ISSUE TITLE
Images dont show

### ISSUE THREAD

**Issue by alfkoblischke** [captcha-com/symfony-captcha-bundle#13]
If works perfectly, when I am logged in. It does not work at all as long as I am logged out. The pictures are not shown. Has this got something to do with the session? Can anybody give me a hint?
Thank you in advance

Symony Vers. 4.x

**Comment by nicolas-san** [comment]
hi @alfkoblischke  :)
have you resolv you image issue ?

**Comment by nicolas-san** [comment]
@alfkoblischke 

If you have not resolve your problem, it's probably a route related issue.

use php bin/console debug:router to see if the route are here,
and don't forget to clear the cache

**Comment by alfkoblischke** [comment]
it was the cache... Thank you very much nicolas.
